chore: Add basic tests
vaadin/quarkus pull request #11
Opened 2021-06-23 08:28 UTC by caalador

Make multiple test modules into integration-tests
Add productionMode test.
Add developmentMode test.
Add test for reusable theme.

part of #4

2021-06-23 08:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/quarkus?pullRequest=11) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/quarkus?pullRequest=11) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/quarkus?pullRequest=11) it.</sub>

2021-06-28 08:11 UTC, denis-anisimov requested changes

2021-06-28 08:11 UTC, denis-anisimov commented on integration-tests/common-test-code/pom.xml
> +</project>
new line

2021-06-28 08:11 UTC, denis-anisimov commented on integration-tests/development/pom.xml
> +</project>
new line

2021-06-28 08:11 UTC, denis-anisimov commented on integration-tests/production/pom.xml
> +</project>
new line

2021-06-28 08:11 UTC, denis-anisimov commented on integration-tests/reusable-theme/src/main/resources/META-INF/resources/themes/reusable-theme/styles.css
> +}
new line

2021-06-28 08:30 UTC, caalador commented
New lines added.

2021-06-29 07:19 UTC, denis-anisimov approved these changes

2021-06-29 07:20 UTC, merged