Skip user `VaadinServlet`s without @WebServlet instead of NPE on `quarkusBuild`
vaadin/quarkus pull request #77
Opened 2022-06-24 09:57 UTC by grossws

## Description

If `VaadinServlet` without `@WebServlet` annotation present (like when `vaadin-cdi` happened to be in classpath) currently `quarkusBuild` will fail with NPE.

This patch skips such servlets with a warning in log.

Fixes #76

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

2022-06-24 09:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/quarkus?pullRequest=77) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/quarkus?pullRequest=77) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/quarkus?pullRequest=77) it.</sub>

2022-06-24 10:50 UTC, mcollovati commented
@grossws thanks for the contribution! Do you mind signing the CLA?

2022-06-24 14:23 UTC, grossws commented
@mcollovati, I've signed CLA, feel free to merge.

2022-06-27 11:47 UTC, taefi requested changes

2022-06-27 11:47 UTC, taefi commented on deployment/src/main/java/com/vaadin/quarkus/deployment/VaadinQuarkusProcessor.java
> +    private static final Logger LOG = LoggerFactory.getLogger(VaadinQuarkusProcessor.class);
```suggestion

    private static final Logger LOG = LoggerFactory.getLogger(VaadinQuarkusProcessor.class);
```

2022-06-27 11:48 UTC, taefi approved these changes

2022-06-27 12:08 UTC, merged