chore: add smoke integration test for quarkus
vaadin/quarkus pull request #9
Opened 2021-06-15 11:10 UTC by caalador

Add the integration test module for quarkus

Closes #1

2021-06-15 11:44 UTC, caalador commented
Requires vaadin/flow#11241

2021-06-22 11:36 UTC, pleku requested changes

2021-06-23 04:00 UTC, caalador commented on integration-tests/pom.xml
> +            <version>${vaadin.flow.version}</version>
I was going to say because it was tested before it existed, but it actually is because we are missing it in the BOM so I made vaadin/flow#11310

2021-06-23 07:38 UTC, caalador commented on integration-tests/pom.xml
> +            <version>${vaadin.flow.version}</version>
done

2021-06-23 08:21 UTC, pleku approved these changes

2021-06-23 08:21 UTC, merged